services:
  - type: web
    name: message-bottle-api
    env: node
    region: oregon
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
